library(xega)
source("F.R")

# print("F1")
# f1 <- F1()
# result1_max <- xegaRun(penv=f1, algorithm="sga", max=TRUE, generations=500, popsize=200, verbose=0)
# result1_min <- xegaRun(penv=f1, algorithm="sga", max=FALSE, generations=500, popsize=200, verbose=0)
# print(result1_max$solution)
# print(result1_min$solution)

# print("F2")
# f2 <- F2()
# result2_max <- xegaRun(penv=f2, algorithm="sga", max=TRUE, generations=500, popsize=200, verbose=0)
# result2_min <- xegaRun(penv=f2, algorithm="sga", max=FALSE, generations=500, popsize=500, verbose=0)
# print(result2_max$solution)
# print(result2_min$solution)

# print("F3")
# f3 <- F3()
# result3_max <- xegaRun(penv=f3, algorithm="sga", max=TRUE, generations=500, popsize=200, verbose=0)
# result3_min <- xegaRun(penv=f3, algorithm="sga", max=FALSE, generations=500, popsize=200, verbose=0)
# print(result3_max$solution)
# print(result3_min$solution)

# print("F4")
# f4 <- F4()
# result4_max <- xegaRun(penv=f4, algorithm="sga", max=TRUE, generations=200, popsize=500, verbose=0)
# result4_min <- xegaRun(penv=f4, algorithm="sga", max=FALSE, generations=200, popsize=500, verbose=0)
# print(result4_max$solution)
# print(result4_min$solution)

print("F5")
f5 <- F5()
result5_max <- xegaRun(penv=f5, algorithm="sga", max=TRUE, generations=500, popsize=200, verbose=0)
result5_min <- xegaRun(penv=f5, algorithm="sga", max=FALSE, generations=500, popsize=200, verbose=0)
print(result5_max$solution)
print(result5_min$solution)